site_name: M<sup>3</sup>G API v1.0 documentation
nav:
  - Intro: index.md
  - Using <i>curl</i>:
          - Download data from M<sup>3</sup>G: curl_download.md
          - Upload data to M<sup>3</sup>G: curl_upload.md
  - Using <i>python</i>:
          - Use e.g. the <i>requests</i> library: python.md
  - Notes: notes.md



theme:
    name: 'material'
    logo: 'm3g.png'
    palette:
      - scheme: 'preference'
        primary: light blue
        accent:  blue
    font:
      text: 'Open Sans'
      code: 'Courier Prime'


extra_css:
  - 'extra.css'

markdown_extensions:
  - attr_list
  - codehilite
